# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools Cython flake8 flake8-pyi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 \
          --per-file-ignores='*.pyi:B,E301,E302,E305,E501,E701,E704,W503' --statistics

  build:
    strategy:
      matrix:
        pyver: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        os: [ubuntu, macos, windows]
      fail-fast: false

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.pyver }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.pyver }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        pip install -r requirements-benchmark.txt

    - name: Compile Cython extensions
      run: |
        python setup.py build_ext --inplace

    - name: Run tests
      run: |
        pytest -v
